version: "2"
services:
    test_trial:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
            - -e
            - https://urgi.versailles.inra.fr/faidare/brapi/v1/ 
            - -t
            - "dXJuOlVSR0kvdHJpYWwvNw=="
        volumes:
         - ./outputdir:/outputdir
    test_study:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
            - -e
            - https://urgi.versailles.inra.fr/faidare/brapi/v1/
            - -s
            - "dXJuOlVSR0kvc3R1ZHkvUklHVzE="
        volumes:
         - ./outputdir:/outputdir
    test_pippa:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
            - -e
            - https://pippa.psb.ugent.be/BrAPIPPA/brapi/v1/
            - -s
            - "VIB_study___55"
        volumes:
         - ./outputdir:/outputdir
    BrAPI2ISA:
        build: ./
        entrypoint: 
            - python
            - /brapi_to_isa.py
        volumes:
         - ./outputdir:/outputdir
