name: Docker Build

on:
  push:
    branches:    
      - master 
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag brapi2isa:$(date +%s)